package Clases;
// Generated 28-ene-2019 9:09:38 by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Almacenes generated by hbm2java
 */
@Entity
@Table(name="Almacenes"
    ,schema="dbo"
    ,catalog="AlmacenesLeo"
)
public class Almacenes  implements java.io.Serializable {

    @Id 
    @Column(name="ID", unique=true, nullable=false)
     private int id;
    @Column(name="Denominacion", nullable=false)
     private Serializable denominacion;
    @Column(name="Direccion", nullable=false)
     private Serializable direccion;
    @Column(name="Capacidad", nullable=false)
     private long capacidad;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="almacenes")
     private Set asignacioneses = new HashSet(0);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="almacenesByIdalmacen2")
     private Set distanciasesForIdalmacen2 = new HashSet(0);
    @OneToMany(fetch=FetchType.LAZY, mappedBy="almacenesByIdalmacen1")
     private Set distanciasesForIdalmacen1 = new HashSet(0);

    public Almacenes() {
    }
    
    public Almacenes(int id, Serializable denominacion, Serializable direccion, long capacidad) {
        this.id = id;
        this.denominacion = denominacion;
        this.direccion = direccion;
        this.capacidad = capacidad;
    }
    public Almacenes(int id, Serializable denominacion, Serializable direccion, long capacidad, Set asignacioneses, Set distanciasesForIdalmacen2, Set distanciasesForIdalmacen1) {
       this.id = id;
       this.denominacion = denominacion;
       this.direccion = direccion;
       this.capacidad = capacidad;
       this.asignacioneses = asignacioneses;
       this.distanciasesForIdalmacen2 = distanciasesForIdalmacen2;
       this.distanciasesForIdalmacen1 = distanciasesForIdalmacen1;
    }     

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    public Serializable getDenominacion() {
        return this.denominacion;
    }
    
    public void setDenominacion(Serializable denominacion) {
        this.denominacion = denominacion;
    }  
    
    public Serializable getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Serializable direccion) {
        this.direccion = direccion;
    }

    public long getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(long capacidad) {
        this.capacidad = capacidad;
    }

    public Set getAsignacioneses() {
        return this.asignacioneses;
    }
    
    public void setAsignacioneses(Set asignacioneses) {
        this.asignacioneses = asignacioneses;
    }

    public Set getDistanciasesForIdalmacen2() {
        return this.distanciasesForIdalmacen2;
    }
    
    public void setDistanciasesForIdalmacen2(Set distanciasesForIdalmacen2) {
        this.distanciasesForIdalmacen2 = distanciasesForIdalmacen2;
    }

    public Set getDistanciasesForIdalmacen1() {
        return this.distanciasesForIdalmacen1;
    }
    
    public void setDistanciasesForIdalmacen1(Set distanciasesForIdalmacen1) {
        this.distanciasesForIdalmacen1 = distanciasesForIdalmacen1;
    }
}


