package Clases;
// Generated 28-ene-2019 9:09:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Envios generated by hbm2java
 */
@Entity
@Table(name="Envios"
    ,schema="dbo"
    ,catalog="AlmacenesLeo"
)
public class Envios  implements java.io.Serializable {


    @Id 
    @Column(name="ID", unique=true, nullable=false)
     private long id;
    @Column(name="NumeroContenedores", nullable=false)
     private int numeroContenedores;
    @Temporal(TemporalType.DATE)
    @Column(name="FechaCreacion", nullable=false, length=10)
     private Date fechaCreacion;
    @Temporal(TemporalType.DATE)
    @Column(name="FechaAsignacion", length=10)
     private Date fechaAsignacion;
    @Column(name="AlmacenPreferido", nullable=false)
     private int almacenPreferido;

    public Envios() {
    }

	
    public Envios(long id, int numeroContenedores, Date fechaCreacion, int almacenPreferido) {
        this.id = id;
        this.numeroContenedores = numeroContenedores;
        this.fechaCreacion = fechaCreacion;
        this.almacenPreferido = almacenPreferido;
    }
    public Envios(long id, int numeroContenedores, Date fechaCreacion, Date fechaAsignacion, int almacenPreferido) {
       this.id = id;
       this.numeroContenedores = numeroContenedores;
       this.fechaCreacion = fechaCreacion;
       this.fechaAsignacion = fechaAsignacion;
       this.almacenPreferido = almacenPreferido;
    }
   
     
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    
    public int getNumeroContenedores() {
        return this.numeroContenedores;
    }
    
    public void setNumeroContenedores(int numeroContenedores) {
        this.numeroContenedores = numeroContenedores;
    }

    
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    public Date getFechaAsignacion() {
        return this.fechaAsignacion;
    }
    
    public void setFechaAsignacion(Date fechaAsignacion) {
        this.fechaAsignacion = fechaAsignacion;
    }

    
    
    public int getAlmacenPreferido() {
        return this.almacenPreferido;
    }
    
    public void setAlmacenPreferido(int almacenPreferido) {
        this.almacenPreferido = almacenPreferido;
    }
}


